apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-app
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx-ingress           # Replace with your actual chart name
      version: 1.3.2            # Replace with your chart version
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: flux-system
      interval: 1m

