apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helloworld
  namespace: helloworld
spec:
  releaseName: helloworld
  interval: 10m
  chart:
    spec:
      chart: helloworld
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: helloworld
      
