apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helloworld
  namespace: helloworld
spec:
  interval: 10m
  chart:
    spec:
      chart: helloworld
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: helloworld
