apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  releaseName: nginx-ingress
  interval: 10m
  chart:
    spec:
      chart: nginx-ingress
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
