---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: helmrepo
  namespace: flux-system
spec:
  interval: 24h
  url: oci://fluxacr1.azurecr.io
  type: oci
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  interval: 30m
  chart:
    spec:
      chart: nginx-ingress
      version: "2.0.0"
      sourceRef:
        kind: HelmRepository
        name: helmrepo
        namespace: flux-system
      interval: 12h
  values:
    controller:
      service:
        type: "NodePort"
    admissionWebhooks:
      enabled: false
